<?php

function mrmilu_dev_templates_theme($existing, $type, $theme, $path) {
  return [
    'dev_template' => [
      'variables' => [],
      'base_hook' => 'dev'
    ],
  ];
}

function mrmilu_dev_templates_theme_suggestions_dev_template_alter(array &$suggestions, array $variables, $hook) {
  $template = \Drupal::routeMatch()->getParameter('template');
  $template = str_replace('-', '_', $template);
  if (!empty($template)) {
    $suggestions[] = 'dev_template__' . $template;
  }
}